config/routes.rb
Rails.application.routes.draw do
  root to: 'index#home'
  resources :movies
  resources :universes
  resources :videos, only: [:new, :index, :destroy]

  get '/fetch_universes' => 'movies#fetch_universes'
  post '/add_universe' => 'movies#add_universe'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :universe, optional: true

  def add_universe(universe_id)
    universe = Universe.find(universe_id)
    self.universe = universe
  end
end

app/models/universe.rb
class Universe < ApplicationRecord
  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def home
    render :"index"
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    ziggeo = Ziggeo.new(ENV['ZIGGEO_KEY'], ENV['ZIGGEO_SECRET'], ENV['ZIGGEO_ENCRYPTION'])
    @videos = ziggeo.videos.index(tags: @movie.id)
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  def fetch_universes
    @movie = Movie.find(add_universe_params[:id])
    @universes = Universe.all
    render :fetch_universe
  end

  def add_universe
    @movie = Movie.find(add_universe_params[:id])
    @movie.add_universe(add_universe_params[:universe_id])
    @movie.save
    redirect_to @movie
  end
  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :summary, :release)
    end

    def add_universe_params
      params.permit(:id, :universe_id)
    end
end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
  before_action :set_universe, only: [:show, :edit, :update, :destroy]

  # GET /universes
  # GET /universes.json
  def index
    @universes = Universe.all
  end

  # GET /universes/1
  # GET /universes/1.json
  def show
  end

  # GET /universes/new
  def new
    @universe = Universe.new
  end

  # GET /universes/1/edit
  def edit
  end

  # POST /universes
  # POST /universes.json
  def create
    @universe = Universe.new(universe_params)

    respond_to do |format|
      if @universe.save
        format.html { redirect_to @universe, notice: 'Universe was successfully created.' }
        format.json { render :show, status: :created, location: @universe }
      else
        format.html { render :new }
        format.json { render json: @universe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universes/1
  # PATCH/PUT /universes/1.json
  def update
    respond_to do |format|
      if @universe.update(universe_params)
        format.html { redirect_to @universe, notice: 'Universe was successfully updated.' }
        format.json { render :show, status: :ok, location: @universe }
      else
        format.html { render :edit }
        format.json { render json: @universe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universes/1
  # DELETE /universes/1.json
  def destroy
    @universe.destroy
    respond_to do |format|
      format.html { redirect_to universes_url, notice: 'Universe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_universe
      @universe = Universe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def universe_params
      params.require(:universe).permit(:name, :blurb)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/universes_helper.rb
module UniversesHelper
end

app/views/index/index.html.erb
<h2>Welcome</h2>

<p>Before The Movie is a Rails web app. The core idea is to make a cohesive viewing experience of trailers.</p>
<p>The movies and movie universes they belong to are user inputed and users can upload trailers to a movie.</p>

<% if Universe.all.count > 1 %>
  <h2>Featured Movie Universe</h2>
  <% random_universe = Universe.all.sample %>
  <%= link_to random_universe.name, random_universe %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Before The Movie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="//assets-cdn.ziggeo.com/v1-stable/ziggeo.css" />
    <script src="//assets-cdn.ziggeo.com/v1-stable/ziggeo.js"></script>
    <script>ZiggeoApi.token = '<%= ENV['ZIGGEO_KEY'] %>';</script>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-dark bg-dark">
      <h1><a href="/">Before the Movie</a></h1>
      <ul>
        <li><h3><%= link_to "Movies", movies_url %></h3></li>
        <li><h3><%= link_to "Universes", universes_url %></h3></li>
      </ul>
    </nav>
    <div id="content">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.text_area :summary, size: "4x4", :class => "form-control",  placeholder: "Movie summary here..." %>
    <%= form.date_select :release, { :start_year => 1913 } %>
    <%= form.submit "Add"%>
  </div>
<% end %>

app/views/movies/_video.html.erb
<div class="card">
  <div class="card-block">
    <ziggeo ziggeo-video='<%= video['token'] %>'
            ziggeo-width="320"
            ziggeo-height="240" ziggeo-popup>
    </ziggeo>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/fetch_universe.html.erb
<% @universes.each do |universe| %>
  <%= universe.name %>
  <%= button_to "Add", { action: "add_universe", id: @movie.id, universe_id: universe.id },
                                method: :add_universe %>
<% end %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.title, movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<h1><%= link_to 'Movies', movies_path %></h1>

<h2><%= @movie.title %></h2>

<ul>
  <li>
    Summary: <%= @movie.summary %>
  </li>
  <li>
    Release date: <%= @movie.release %>
  </li>
  <% if @movie.universe %>
    <li>
      Universe: <%= link_to @movie.universe.name, @movie.universe %>
    </li>
  <% end %>
</ul>

<h3><%= link_to "Add to a Universe", :controller => "movies", :action => "fetch_universes", :id => @movie.id  %></h3>

<h3>Trailers</h3>
<%= render partial: 'video', collection: @videos, as: :video %>

<h3>Add Trailer</h3>
<ziggeo ziggeo-limit="60"
        ziggeo-width="320"
        ziggeo-height="240"
        ziggeo-perms="allowupload"
        ziggeo-tags="<%= @movie.id %>"></ziggeo>

<%= link_to 'Edit', edit_movie_path(@movie) %> |

app/views/universes/_form.html.erb
<%= form_with(model: universe, local: true) do |form| %>
  <% if universe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(universe.errors.count, "error") %> prohibited this universe from being saved:</h2>

      <ul>
      <% universe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.text_area :blurb, size: "4x4", :class => placeholder: "Movie universe summary here..."%>
    <%= form.submit %>
  </div>
<% end %>

app/views/universes/edit.html.erb
<h1>Editing Universe</h1>

<%= render 'form', universe: @universe %>

<%= link_to 'Show', @universe %> |
<%= link_to 'Back', universes_path %>

app/views/universes/index.html.erb
<h1>Universes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @universes.each do |universe| %>
      <tr>
        <td><%= link_to  universe.name, universe %></td>
        <td><%= link_to 'Edit', edit_universe_path(universe) %></td>
        <td><%= link_to 'Destroy', universe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Universe', new_universe_path %>

app/views/universes/new.html.erb
<h1>New Universe</h1>

<%= render 'form', universe: @universe %>

<%= link_to 'Back', universes_path %>

app/views/universes/show.html.erb
<h1><%= link_to 'Universes', universes_path %></h1>

<h2><%= @universe.name %></h2>

<%= @universe.blurb %>
<%= link_to 'Edit', edit_universe_path(@universe) %> |

<% @universe.movies. each do |movie| %>
  <%= link_to movie.title, movie %>
<% end %>